git:
  privateKeyFilePath: "/etc/git/private_key"
store:
  directory: "/etc/analyzer/jobs"
docker:
  host: "unix:///var/run/docker.sock"
  apiVersion: 1.41
notification:
  webhook: ${NOTIFY_WEBHOOK}
default:
  project:
    name: ${JOB_PROJECT_NAME}
    url: ${JOB_PROJECT_URL}
    branch: ${JOB_PROJECT_BRANCH}
    sonarFilePath: ${JOB_PROJECT_FILE_PATH}
    mode: ${JOB_PROJECT_MODE}
    description: ${JOB_PROJECT_DESCRIPTION}
  sonar:
    enable: ${SONAR_ENABLE}
    url: ${SONAR_URL}
    login: ${SONAR_LOGIN}
    password: ${SONAR_PASSWORD}