git-repository:
  syncTimeCron: "0/30 * * * * ?"
  storeDirectory: "/etc/analyzer/scheduler/"
  repository:
    url: "git@172.17.189.70:wangyj/riil-sonar.git"
    branch: "develop"
    taskFilePath: "/tasks/develop.yaml"
    privateKeyFilePath: "/etc/git/private_key"
docker:
  host: "unix:///var/run/docker.sock"
  apiVersion: 1.41
scheduler:
  maxParallel: 10
  maxJobWaitTimeSecond: 7200 # 2小时的最大等待时长，单位为秒
job:
  tag: 1.0
  repository: 172.17.162.231/devops/analyzer-job
sweep:
  matchExpressions:
    operator: NotIn
    values:
      - ".*analyzer-job.*"
  container:
    timeCron: "0/10 * * * * ?"
    timeoutHours: 1
    matches:
      - ".*analyzer-job.*"
      - ".*sonar.*"
  image:
    timeCron: "0/10 * * * * ?"
    matches:
      - ".*<none>.*"
sonar:
  enable: true
  url: "http://172.17.206.162:30090"
  login: "admin"
  password: "3ed$RF5tg"