git:
  privateKeyFilePath: "/etc/git/private_key"
store:
  directory: "/etc/sonars/jobs"
docker:
  host: "unix:///var/run/docker.sock"
  apiVersion: 1.41
notification:
  webhook: "https://open.feishu.cn/open-apis/bot/v2/hook/ed495d44-4048-4bb9-afd8-233235b53437"
default:
  project:
    name: ${JOB_PROJECT_NAME}
    url: ${JOB_PROJECT_URL}
    branch: ${JOB_PROJECT_BRANCH}
    sonarFileUrl: ${JOB_PROJECT_FILE_URL}
    mode: ${JOB_PROJECT_MODE}
    description: ${JOB_PROJECT_DESCRIPTION}
  sonar:
    enable: ${SONAR_ENABLE}
    url: ${SONAR_URL}
    login: ${SONAR_LOGIN}
    password: ${SONAR_PASSWORD}