git:
#   username: "v-huhouhua"
#   password: "huhouhua"
   username: "v-huhouhua@ruijie.com.cn"
   password: "12345678"
store:
  directory: "/etc/sonars/jobs"
#  directory: "I:\\test\\project"
#  directory: "D:\\demo\\job"
docker:
#  host: tcp://172.17.163.194:2375
  host: "unix:///var/run/docker.sock"
  apiVersion: 1.41
notification:
  webhook: "https://open.feishu.cn/open-apis/bot/v2/hook/ed495d44-4048-4bb9-afd8-233235b53437"